# User Details
spring.datasource.username=whoisashif
spring.datasource.password=whoisashif

# Spring Security
spring.security.user.name=whoisashif
spring.security.user.password=whoisashif

# Secret Key
jwt.secret=MyVeryLongSecretKeyToCre@teJVVTt0k3n
jwt.expiration=86400000